spring.application.name=SpringBoot_REST_API_Blueprints

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/blueprints
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Schema Initialization
spring.sql.init.mode=always
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# JWT Security Configuration
blueprints.security.issuer=https://decsis-eci/blueprints
blueprints.security.jwt.token-ttl-seconds=7200
spring.main.allow-bean-definition-overriding=true
